# Setup
# Specify the author for blog posts
author:
  name: bijumon
  url: https://bijumon.github.io/about/
  email: me@gee.mail

title: Firehose Weekly
tagline: fuel for the dev firehose
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://bijumon.github.io"
permalink: "pretty"

plugins:
  - jekyll-feed

markdown: Commonmarker
commonmarker:
  parse:
    smart: true
  render:
    hardbreaks: true
  extension:
    header_ids: ""
    strikethrough: true
    table: true
    autolink: true
    tasklist: true
    footnotes: true
    superscript: true
    subscript: true
    description_lists: true
    underline: true
    spoiler: true
    shortcodes: true
    alerts: true
  rouge:
    css_class: 'highlight'
    line_numbers: false
    wrap: true
    guess_lang: true

exclude:
    - archive
    - Readme.md
    - todo.md
    - Gemfile
    - Gemfile.lock

# frontmatter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: "notes"  # Path to apply the default
      type: "pages"  # Only apply to pages, not posts
    values:
      categories: "notes"